deployments:
  - name: development
    description: development
    # Automatically trigger deploy on default branch passing
    on_push: true

  - name: staging
    description: staging
    # auto-deploy from the staging branch to the staging environment, when tests pass
    on_push: true
    on_push_branch: staging

  - name: production
    description: production
    # requires a manual deploy
